/**
 * Poseidon hash over the BLS12-381 SCALAR field `r`.
 *
 * ============================================================================
 * INVARIANT #1 / #13 - PARAMETER PARITY (FUND/PRIVACY CRITICAL)
 * ============================================================================
 * This module MUST NOT use circomlibjs' default Poseidon (BN254). The parameters
 * below come from `./poseidon-params.ts`, which is GENERATED by
 * `scripts/gen-poseidon-params.mjs` for the BLS12-381 scalar field
 *
 *   r = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
 *
 * and is byte-identical to `circuits/lib/poseidon_constants.circom`. The
 * permutation here mirrors `circuits/lib/poseidon_bls.circom` exactly. The parity
 * gate (`sdk/test/poseidon.test.ts` + `scripts/test-poseidon-parity.ts`) asserts
 * the circuit and this SDK produce the same digest.
 *
 * Provenance: fresh, self-consistent (not matched to external test vectors).
 * Security: alpha=5 is a permutation (gcd(5, r-1)=1); MDS is a Cauchy matrix.
 *
 * SECURITY (invariant #8): Poseidon inputs frequently include secrets
 * (`owner_sk`, `rho`, `r_note`, plaintext `value`). NEVER log inputs/outputs.
 * ============================================================================
 */

import type { Fr } from './types.js';
import { P, ALPHA, RF, RP, C, M } from './poseidon-params.js';

/** The BLS12-381 scalar field modulus `r`. */
export const BLS12_381_SCALAR_FIELD_MODULUS: bigint = P;

/** Convenience alias used throughout the SDK. */
export const FR_MODULUS = BLS12_381_SCALAR_FIELD_MODULUS;

/** Documented Poseidon configuration (the actual constants live in poseidon-params.ts). */
export const POSEIDON_BLS_PARAMS = {
  field: 'BLS12-381-scalar-field-r' as const,
  alpha: ALPHA,
  fullRounds: RF,
  partialRoundsByWidth: RP,
  provenance: 'fresh/self-consistent (Grain LFSR + Cauchy MDS)' as const,
  widthsInUse: [2, 3, 6] as const,
} as const;

/** Reduce a bigint into the canonical `[0, r)` representative. */
export function toField(x: bigint): Fr {
  const m = x % FR_MODULUS;
  return m >= 0n ? m : m + FR_MODULUS;
}

/** x^5 mod r (the S-box). */
function sbox(x: bigint): bigint {
  const x2 = (x * x) % P;
  const x4 = (x2 * x2) % P;
  return (x4 * x) % P;
}

/**
 * Poseidon over the BLS12-381 scalar field.
 *
 * Width `t = inputs.length + 1`; supported arities are 1, 2, and 5 (t = 2, 3, 6),
 * the ones Finnes uses (asset_id/owner_pk: 1; nullifier/Merkle node: 2;
 * commitment: 5). The capacity element is initialized to 0.
 *
 * @param inputs field elements (each reduced into `[0, r)`).
 * @returns the Poseidon digest in `[0, r)`.
 */
export function poseidonBLS(inputs: readonly Fr[]): Fr {
  const t = inputs.length + 1;
  const c = C[t];
  const m = M[t];
  const rp = RP[t];
  if (c === undefined || m === undefined || rp === undefined) {
    throw new Error(
      `poseidonBLS: unsupported arity ${inputs.length} (t=${t}); ` +
        `available widths: ${POSEIDON_BLS_PARAMS.widthsInUse.join(', ')}`,
    );
  }
  const nRounds = RF + rp;
  const half = RF / 2;

  // state[0] = capacity (0); state[1..] = inputs.
  let state: bigint[] = [0n, ...inputs.map(toField)];

  for (let r = 0; r < nRounds; r++) {
    // add round constants
    for (let i = 0; i < t; i++) state[i] = (state[i]! + c[r * t + i]!) % P;
    // S-box: full rounds hit every element, partial rounds only element 0
    const full = r < half || r >= half + rp;
    if (full) {
      for (let i = 0; i < t; i++) state[i] = sbox(state[i]!);
    } else {
      state[0] = sbox(state[0]!);
    }
    // mix: next = M * state
    const next: bigint[] = new Array(t).fill(0n);
    for (let i = 0; i < t; i++) {
      let acc = 0n;
      for (let j = 0; j < t; j++) acc = (acc + m[i]![j]! * state[j]!) % P;
      next[i] = acc;
    }
    state = next;
  }
  return state[0]!;
}

/**
 * FIXED cross-implementation parity vector (invariant #13 CI gate).
 * `expected` is the digest produced by BOTH this SDK and the circuit for `inputs`.
 * Locked; regenerating Poseidon params is a parity-breaking event that must
 * update this value (and trigger a fresh ceremony).
 */
export const POSEIDON_BLS_TEST_VECTOR: {
  readonly inputs: readonly Fr[];
  readonly expected: Fr;
  readonly finalized: boolean;
} = {
  inputs: [1n, 2n],
  // Verified equal in circuit (circom --prime bls12381) and SDK by
  // scripts/test-poseidon-parity.ts.
  expected: 1539466174953200397849885941806203218514759356197876052928772286378091849564n,
  finalized: true,
};
